---
title: "Tidy Tuesday Appa"
tags: 
- R
- Tidy Tuesday
categories:
- R
- Tidy Tuesday
output: 
  html_notebook:
    theme: cosmo
  blogdown::html_page:
      toc: true
      fig_width: 6
      dev: "svg"
---


## Load data and packages
```{r}
library(tibble)
library(dplyr)
library(tidyr)
library(stringr)
library(purrr)

library(igraph)
library(tidygraph)
library(ggplot2)
library(ggraph)

avatar <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-08-11/avatar.csv')
scene_description <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-08-11/scene_description.csv')
```

Let's make a simple graph to see the connection among characters and some important concepts in the series. The most times the character said something, stronger will be the connection between them. This will show in proximity and size of the connection in the network.

```{r}
avatar <- avatar %>% 
          filter(character != "Scene Description")
```

```{r}
characters <- c("Aang", "Sokka", "Katara", "Toph", "Zuko",
                 "Iroh", "Ozai","Azula")
words_of_interest <- c("Avatar", "Aang", "Sokka", "Katara", 
                       "Toph", "Zuko", "Iroh", "Fire Lord",
                       "Azula", "kill", "Sozin's Comet", 
                       "save", "Earth Kingdom", "spirit",
                       "Appa","bison" ,"Ozai", "moon",
                       "agni kai", "bending", "water tribe",
                       "balance")

tribes <- c("concept", "air", "water","water",
            "earth", "fire", "fire", "fire",
            "fire", "concept","fire",
            "concept", "earth", "concept",
            "air", "air", "fire", "water",
            "fire", "concept", "water",
            "balance")

levels_tribes <- sort(unique(tribes))
tribes <- data.frame(words = words_of_interest, 
                     tribes = factor(tribes,
                                     levels = levels_tribes,
                                     ordered = TRUE
                                     )
                     )
  

adjacencies <- rep(list(words_of_interest),length(characters))
names(adjacencies) <- characters
adjacencies <- adjacencies %>% 
  enframe("character", "word") %>% 
  unnest(word) %>% 
   nest_join(select(avatar,character, character_words),
             "character", name = "lines") %>% 
  group_by(character, word) %>% 
  mutate(weight = map_dbl(lines, ~sum(str_count(.$character_words, word)))) %>% 
  filter(weight > 4, character != word) %>% 
  select(-lines)
  

counter <-  function(character, word){
          sum(str_count(filter(avatar,
                               character == character)$character_words,
                        word))
}

adjacencies3 <- adjacencies2 %>% 
  group_by(character, word) %>% 
  mutate(what = map_dbl(lines, ~sum(str_count(.$character_words, word))))
```

```{r}
theme_set(theme_bw(16))

avatar_fill <- function (...) { scale_fill_manual(values =  c(
                               "#F1B84A", "grey20", 
                               "#4FA24C", "#900B0B",
                               "#4A82CB")
) }

windowsFonts(avatar_font = windowsFont("Herculanum"))

graph <- graph_from_data_frame(adjacencies)
graph <- as_tbl_graph(graph)
graph <- left_join(graph, tribes, by = c(name = "words"))

ggraph(graph, layout = 'fr')+
    geom_edge_link(aes(width = weight), color = 'grey70')+
    geom_node_point()+
    geom_node_label(aes(label = name, fill = tribes),
                    color = "white", fontface = "bold",
                    family = "avatar_font", size = 6)+
   avatar_fill()
```

```{r}
avatar %>%
group_by(book) %>%
summarise(imdb = mean(imdb_rating, na.rm = T)) %>% 
ggplot()

avatar %>% 
  ggplot(aes(book, imdb_rating, fill = book))+
  geom_boxplot()+
  avatar_fill()
```

